// This file is auto-generated by rpcc.
//
// Copyright (C) 2021 Markku Rossi.
//
// All rights reserved.
//

package ipc

// CKAttributeType defines basic protocol type CK_ATTRIBUTE_TYPE.
type CKAttributeType uint32

// CKBbool defines basic protocol type CK_BBOOL.
type CKBbool bool

// CKByte defines basic protocol type CK_BYTE.
type CKByte byte

// CKChar defines basic protocol type CK_CHAR.
type CKChar byte

// CKFlags defines basic protocol type CK_FLAGS.
type CKFlags uint32

// CKMechanismType defines basic protocol type CK_MECHANISM_TYPE.
type CKMechanismType uint32

// CKObjectHandle defines basic protocol type CK_OBJECT_HANDLE.
type CKObjectHandle uint32

// CKSessionHandle defines basic protocol type CK_SESSION_HANDLE.
type CKSessionHandle uint32

// CKSlotID defines basic protocol type CK_SLOT_ID.
type CKSlotID uint32

// CKUlong defines basic protocol type CK_ULONG.
type CKUlong uint32

// CKUTF8Char defines basic protocol type CK_UTF8CHAR.
type CKUTF8Char byte

// CKVoidPtr defines basic protocol type CK_VOID_PTR.
type CKVoidPtr byte

// CKAttribute defines compound protocol type CK_ATTRIBUTE.
type CKAttribute struct {
	Type   CKAttributeType
	PValue []CKVoidPtr
}

// CKInfo defines compound protocol type CK_INFO.
type CKInfo struct {
	CryptokiVersion    CKVersion
	ManufacturerID     [32]CKUTF8Char
	Flags              CKFlags
	LibraryDescription [32]CKUTF8Char
	LibraryVersion     CKVersion
}

// CKMechanismInfo defines compound protocol type CK_MECHANISM_INFO.
type CKMechanismInfo struct {
	UlMinKeySize CKUlong
	UlMaxKeySize CKUlong
	Flags        CKFlags
}

// CKSlotInfo defines compound protocol type CK_SLOT_INFO.
type CKSlotInfo struct {
	SlotDescription [64]CKUTF8Char
	ManufacturerID  [32]CKUTF8Char
	Flags           CKFlags
	HardwareVersion CKVersion
	FirmwareVersion CKVersion
}

// CKTokenInfo defines compound protocol type CK_TOKEN_INFO.
type CKTokenInfo struct {
	Label                [32]CKUTF8Char
	ManufacturerID       [32]CKUTF8Char
	Model                [16]CKUTF8Char
	SerialNumber         [16]CKChar
	Flags                CKFlags
	UlMaxSessionCount    CKUlong
	UlSessionCount       CKUlong
	UlMaxRwSessionCount  CKUlong
	UlRwSessionCount     CKUlong
	UlMaxPinLen          CKUlong
	UlMinPinLen          CKUlong
	UlTotalPublicMemory  CKUlong
	UlFreePublicMemory   CKUlong
	UlTotalPrivateMemory CKUlong
	UlFreePrivateMemory  CKUlong
	HardwareVersion      CKVersion
	FirmwareVersion      CKVersion
	UtcTime              [16]CKChar
}

// CKVersion defines compound protocol type CK_VERSION.
type CKVersion struct {
	Major CKByte
	Minor CKByte
}

// InitializeResp defines the result of C_Initialize.
type InitializeResp struct {
	NumSlots CKUlong
}

// GetSlotListReq defines the arguments of C_GetSlotList.
type GetSlotListReq struct {
	TokenPresent CKBbool
}

// GetSlotListResp defines the result of C_GetSlotList.
type GetSlotListResp struct {
	PSlotList []CKSlotID
}

// GetSlotInfoReq defines the arguments of C_GetSlotInfo.
type GetSlotInfoReq struct {
	SlotID CKSlotID
}

// GetSlotInfoResp defines the result of C_GetSlotInfo.
type GetSlotInfoResp struct {
	PInfo CKSlotInfo
}

// InitTokenReq defines the arguments of C_InitToken.
type InitTokenReq struct {
	SlotID CKSlotID
	PPin   []CKUTF8Char
	PLabel [32]CKUTF8Char
}

// InitPINReq defines the arguments of C_InitPIN.
type InitPINReq struct {
	PPin []CKUTF8Char
}

// SetPINReq defines the arguments of C_SetPIN.
type SetPINReq struct {
	POldPin []CKUTF8Char
	PNewPin []CKUTF8Char
}

// CreateObjectReq defines the arguments of C_CreateObject.
type CreateObjectReq struct {
	PTemplate []CKAttribute
}

// CreateObjectResp defines the result of C_CreateObject.
type CreateObjectResp struct {
	PhObject CKObjectHandle
}

// CopyObjectReq defines the arguments of C_CopyObject.
type CopyObjectReq struct {
	HObject   CKObjectHandle
	PTemplate []CKAttribute
}

// CopyObjectResp defines the result of C_CopyObject.
type CopyObjectResp struct {
	PhNewObject CKObjectHandle
}

// DestroyObjectReq defines the arguments of C_DestroyObject.
type DestroyObjectReq struct {
	HObject CKObjectHandle
}

// GetObjectSizeReq defines the arguments of C_GetObjectSize.
type GetObjectSizeReq struct {
	HObject CKObjectHandle
}

// GetObjectSizeResp defines the result of C_GetObjectSize.
type GetObjectSizeResp struct {
	PulSize CKUlong
}

// GetAttributeValueReq defines the arguments of C_GetAttributeValue.
type GetAttributeValueReq struct {
	HObject   CKObjectHandle
	PTemplate []CKAttribute
}

// GetAttributeValueResp defines the result of C_GetAttributeValue.
type GetAttributeValueResp struct {
	PTemplate []CKAttribute
}

// SetAttributeValueReq defines the arguments of C_SetAttributeValue.
type SetAttributeValueReq struct {
	HObject   CKObjectHandle
	PTemplate []CKAttribute
}

// FindObjectsInitReq defines the arguments of C_FindObjectsInit.
type FindObjectsInitReq struct {
	PTemplate []CKAttribute
}

// FindObjectsReq defines the arguments of C_FindObjects.
type FindObjectsReq struct {
	UlMaxObjectCount CKUlong
}

// FindObjectsResp defines the result of C_FindObjects.
type FindObjectsResp struct {
	PhObject []CKObjectHandle
}

// Provider defines the PKCS #11 provider interface.
type Provider interface {
	Initialize() (*InitializeResp, error)
	GetSlotList(req *GetSlotListReq) (*GetSlotListResp, error)
	GetSlotInfo(req *GetSlotInfoReq) (*GetSlotInfoResp, error)
	InitToken(req *InitTokenReq) error
	InitPIN(req *InitPINReq) error
	SetPIN(req *SetPINReq) error
	CreateObject(req *CreateObjectReq) (*CreateObjectResp, error)
	CopyObject(req *CopyObjectReq) (*CopyObjectResp, error)
	DestroyObject(req *DestroyObjectReq) error
	GetObjectSize(req *GetObjectSizeReq) (*GetObjectSizeResp, error)
	GetAttributeValue(req *GetAttributeValueReq) (*GetAttributeValueResp, error)
	SetAttributeValue(req *SetAttributeValueReq) error
	FindObjectsInit(req *FindObjectsInitReq) error
	FindObjects(req *FindObjectsReq) (*FindObjectsResp, error)
	FindObjectsFinal() error
}

// Base provides a dummy implementation of the Provider interface.
type Base struct{}

// Initialize implements the Provider.Initialize().
func (b *Base) Initialize() (*InitializeResp, error) {
	return nil, ErrFunctionNotSupported
}

// GetSlotList implements the Provider.GetSlotList().
func (b *Base) GetSlotList(req *GetSlotListReq) (*GetSlotListResp, error) {
	return nil, ErrFunctionNotSupported
}

// GetSlotInfo implements the Provider.GetSlotInfo().
func (b *Base) GetSlotInfo(req *GetSlotInfoReq) (*GetSlotInfoResp, error) {
	return nil, ErrFunctionNotSupported
}

// InitToken implements the Provider.InitToken().
func (b *Base) InitToken(req *InitTokenReq) error {
	return ErrFunctionNotSupported
}

// InitPIN implements the Provider.InitPIN().
func (b *Base) InitPIN(req *InitPINReq) error {
	return ErrFunctionNotSupported
}

// SetPIN implements the Provider.SetPIN().
func (b *Base) SetPIN(req *SetPINReq) error {
	return ErrFunctionNotSupported
}

// CreateObject implements the Provider.CreateObject().
func (b *Base) CreateObject(req *CreateObjectReq) (*CreateObjectResp, error) {
	return nil, ErrFunctionNotSupported
}

// CopyObject implements the Provider.CopyObject().
func (b *Base) CopyObject(req *CopyObjectReq) (*CopyObjectResp, error) {
	return nil, ErrFunctionNotSupported
}

// DestroyObject implements the Provider.DestroyObject().
func (b *Base) DestroyObject(req *DestroyObjectReq) error {
	return ErrFunctionNotSupported
}

// GetObjectSize implements the Provider.GetObjectSize().
func (b *Base) GetObjectSize(req *GetObjectSizeReq) (*GetObjectSizeResp, error) {
	return nil, ErrFunctionNotSupported
}

// GetAttributeValue implements the Provider.GetAttributeValue().
func (b *Base) GetAttributeValue(req *GetAttributeValueReq) (*GetAttributeValueResp, error) {
	return nil, ErrFunctionNotSupported
}

// SetAttributeValue implements the Provider.SetAttributeValue().
func (b *Base) SetAttributeValue(req *SetAttributeValueReq) error {
	return ErrFunctionNotSupported
}

// FindObjectsInit implements the Provider.FindObjectsInit().
func (b *Base) FindObjectsInit(req *FindObjectsInitReq) error {
	return ErrFunctionNotSupported
}

// FindObjects implements the Provider.FindObjects().
func (b *Base) FindObjects(req *FindObjectsReq) (*FindObjectsResp, error) {
	return nil, ErrFunctionNotSupported
}

// FindObjectsFinal implements the Provider.FindObjectsFinal().
func (b *Base) FindObjectsFinal() error {
	return ErrFunctionNotSupported
}

var msgTypeNames = map[Type]string{
	0xc0050401: "Initialize",
	0xc0050501: "GetSlotList",
	0xc0050502: "GetSlotInfo",
	0xc0050507: "InitToken",
	0xc0050508: "InitPIN",
	0xc0050509: "SetPIN",
	0xc0050701: "CreateObject",
	0xc0050702: "CopyObject",
	0xc0050703: "DestroyObject",
	0xc0050704: "GetObjectSize",
	0xc0050705: "GetAttributeValue",
	0xc0050706: "SetAttributeValue",
	0xc0050707: "FindObjectsInit",
	0xc0050708: "FindObjects",
	0xc0050709: "FindObjectsFinal",
}

// Dispatch dispatches the message to provider and returns the message
// response.
func Dispatch(p Provider, msgType Type, req []byte) (CKRV, []byte) {
	resp, err := call(p, msgType, req)
	if err != nil {
		ckrv, ok := err.(CKRV)
		if ok {
			return ckrv, nil
		}
		return ErrFunctionNotSupported, nil
	}
	return ErrOk, resp
}

func call(p Provider, msgType Type, data []byte) ([]byte, error) {
	switch msgType {
	case 0xc0050401: // Initialize
		resp, err := p.Initialize()
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050501: // GetSlotList
		var req GetSlotListReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.GetSlotList(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050502: // GetSlotInfo
		var req GetSlotInfoReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.GetSlotInfo(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050507: // InitToken
		var req InitTokenReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.InitToken(&req)

	case 0xc0050508: // InitPIN
		var req InitPINReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.InitPIN(&req)

	case 0xc0050509: // SetPIN
		var req SetPINReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.SetPIN(&req)

	case 0xc0050701: // CreateObject
		var req CreateObjectReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.CreateObject(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050702: // CopyObject
		var req CopyObjectReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.CopyObject(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050703: // DestroyObject
		var req DestroyObjectReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.DestroyObject(&req)

	case 0xc0050704: // GetObjectSize
		var req GetObjectSizeReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.GetObjectSize(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050705: // GetAttributeValue
		var req GetAttributeValueReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.GetAttributeValue(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050706: // SetAttributeValue
		var req SetAttributeValueReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.SetAttributeValue(&req)

	case 0xc0050707: // FindObjectsInit
		var req FindObjectsInitReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		return nil, p.FindObjectsInit(&req)

	case 0xc0050708: // FindObjects
		var req FindObjectsReq
		if err := Unmarshal(data, &req); err != nil {
			return nil, err
		}
		resp, err := p.FindObjects(&req)
		if err != nil {
			return nil, err
		}
		return Marshal(resp)

	case 0xc0050709: // FindObjectsFinal
		return nil, p.FindObjectsFinal()

	default:
		return nil, ErrFunctionNotSupported
	}
}
